import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.BufferedInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.util.Random;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.Timer;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author MarkM
 */
public class Pikachu extends javax.swing.JFrame {
    

    /**
     * Creates new form Pikachu
     */
    public Pikachu() {
        initComponents();
        setIconImage();
        playSound("song.wav");
        Eattimer s=new Eattimer();
        s.start();
        
        jProgressBar1.setMinimum(0);
        jProgressBar1.setMaximum(150);
        jProgressBar1.setValue(30);

        jProgressBar1.addChangeListener(new ChangeListener() {
            @Override
            public void stateChanged(ChangeEvent e) {
                checkProgressBarValue();
            }

           private void checkProgressBarValue() {
            int value = jProgressBar1.getValue();
            if (value == 0) {
                playSound("dead.wav");
                System.out.println("Restarting Game");
                JOptionPane.showMessageDialog(null, "Pikachu died of hunger");          
                restartProgram();
            } else if (value == 150) {
                playSound("dead.wav");
                System.out.println("Restarting Game");
                JOptionPane.showMessageDialog(null, "Pikachu died of obesity");
                restartProgram();
            }
        }

        private void restartProgram() {
            String java = System.getProperty("java.home") + "/bin/java";
            String className = Pikachu.class.getName();

            try {
                new ProcessBuilder(java, "-cp", System.getProperty("java.class.path"), className).start();
            } catch (IOException e) {
                e.printStackTrace();
            }
            dispose();
            System.exit(0);
        }

            private void stopSound(String soundwav) {
                throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
            }

            private void stopCurrentlyPlayingSound() {
                throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
            }

});

        updateImage();
          }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jProgressBar1 = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pikachu Simulator ");
        setBackground(new java.awt.Color(248, 199, 24));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pika.gif"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, -1, -1));

        jLabel4.setFont(new java.awt.Font("Minecraftia", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, -1, -1));

        jButton2.setBackground(new java.awt.Color(255, 0, 0));
        jButton2.setFont(new java.awt.Font("Ubuntu", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Sleep");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 470, 70, 20));

        jButton3.setBackground(new java.awt.Color(255, 0, 0));
        jButton3.setFont(new java.awt.Font("Ubuntu", 1, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Play");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 370, 70, 20));

        jButton1.setBackground(new java.awt.Color(255, 0, 0));
        jButton1.setFont(new java.awt.Font("Ubuntu", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Feed");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 470, 70, 20));

        jLabel3.setFont(new java.awt.Font("Minecraftia", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("0");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 440, -1, -1));

        jLabel6.setFont(new java.awt.Font("Minecraftia", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("0");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 440, -1, -1));

        jLabel7.setFont(new java.awt.Font("Minecraftia", 1, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("0");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 400, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gba.png"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 630));

        jPanel4.setBackground(new java.awt.Color(248, 199, 24));

        jProgressBar1.setBackground(new java.awt.Color(51, 51, 51));
        jProgressBar1.setForeground(new java.awt.Color(102, 255, 102));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(192, Short.MAX_VALUE)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 240, 210));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       playSound("button.wav");
         jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/eat.gif"))); // NOI18N
        Random w = new Random(); 
        int food = w.nextInt(100) + 1; 
        addFood(food + "");

        Thread i = new Thread() {
            public void run() {
                try {
                    Thread.sleep(5000);    
                } catch(Exception e) {
                    System.out.println(e);
                }
                updateImage();
            }
        };
        i.start();

        Eattimer s = new Eattimer();
        s.start();
        jLabel4.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        playSound("button.wav");
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/play.gif"))); 
         Random random = new Random();
         int deductionAmount = random.nextInt(101) + 50; 
         int currentProgress = jProgressBar1.getValue();
         int newProgress = Math.max(currentProgress - deductionAmount, 0);
         jProgressBar1.setValue(newProgress);
         
         Timer gifTimer = new Timer(5000, new ActionListener() {
             @Override
             public void actionPerformed(ActionEvent e) {
                 jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pika.gif"))); 

                 Timer countdownTimer = new Timer(1000, new ActionListener() {
                     int countdown = 120;

                     @Override
                     public void actionPerformed(ActionEvent e) {
                         jLabel7.setText(String.valueOf(countdown));
                         countdown--;

                         if (countdown < 0) {
                             ((Timer) e.getSource()).stop();
                             jLabel7.setText("0");
                             jButton3.setEnabled(true);
                         }
                     }
                 });
                 countdownTimer.start();
             }
         });
         gifTimer.setRepeats(false);
         gifTimer.start();

         jButton3.setEnabled(false);

         jButton3ClickCount++;

         if (jButton3ClickCount == 2) {
             jButton2.setEnabled(true);
         } else if (jButton3ClickCount == 3) {
             jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dead.gif"))); 

             UpdateImageListener updateImageListener = new UpdateImageListener();

             Timer deadGifTimer = new Timer(100000, new ActionListener() {
                 @Override
                 public void actionPerformed(ActionEvent e) {
                     jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/play.gif"))); 
                 }
             });
             deadGifTimer.setRepeats(false);
             deadGifTimer.start();

             Timer disableUpdateImageTimer = new Timer(100000, new ActionListener() {
                 @Override
                 public void actionPerformed(ActionEvent e) {
                     jButton3.removeActionListener(updateImageListener);
                 }
             });
             disableUpdateImageTimer.setRepeats(false);
             disableUpdateImageTimer.start();
         }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
          jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sleep.gif"))); 
            playSound("button.wav");
            jButton1.setEnabled(false);
            jButton2.setEnabled(false);
            jButton3.setEnabled(false);

            Timer gifTimer = new Timer(1000, new ActionListener() {
                int countdown = 90;

                @Override
                public void actionPerformed(ActionEvent e) {
                    jLabel6.setText(String.valueOf(countdown));
                    countdown--;

                    if (countdown < 0) {
                        ((Timer) e.getSource()).stop();
                        jButton1.setEnabled(true);
                        jButton3.setEnabled(true);
                    }
                }
            });
            gifTimer.start();

            jButton1.setEnabled(false);
            Timer buttonTimer = new Timer(90000, new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    jButton1.setEnabled(true);
                }
            });
            buttonTimer.setRepeats(false);
            buttonTimer.start();

            Random random = new Random();
            int deductionAmount = random.nextInt(51) + 30;
            int currentProgress = jProgressBar1.getValue();
            int newProgress = Math.max(currentProgress - deductionAmount, 0);
            jProgressBar1.setValue(newProgress);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
     
private void updateImage() {
    int value = jProgressBar1.getValue();
    if (value == 0) {
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dead.gif")));
    } else if (value == 150) {
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pika.gif")));
    } else {
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pika.gif")));
    }
}//end update image

  private void playSound(String filename) {
    try (InputStream inputStream = getClass().getResourceAsStream("/" + filename)) {
        if (inputStream != null) {
            AudioInputStream audioStream = AudioSystem.getAudioInputStream(new BufferedInputStream(inputStream));
            Clip clip = AudioSystem.getClip();
            clip.open(audioStream);
            clip.start();
        } else {
            System.err.println("File not found: " + filename);
        }
    } catch (Exception ex) {
        ex.printStackTrace();
    }
}

//eat timer
class Eattimer extends Thread{
      public void run(){
      int t=10;
      do{
      changeEattimer(t);    
          
     try{
      Thread.sleep(1000);    
      }catch(Exception e){
      System.out.println(e);
      }
           
      t--;  
      }while(t>=0);
       
      if(t<0){
      hungry();
      }
      
      
      }
}//end eat timer

private void changeEattimer(int x){
     SwingUtilities.invokeLater(new Runnable(){
     public void run(){
      jLabel3.setText(x+"");   
      jButton1.setEnabled(false);
       }
     
     });
}//end eat timer

private void hungry(){
     SwingUtilities.invokeLater(new Runnable(){
      public void run(){
      jButton1.setEnabled(true);
      jLabel4.setText("I'm hungry :(");
      jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tired.gif")));
      }
     });
}

private void addFood(String x){
   int curr=jProgressBar1.getValue();
   jProgressBar1.setValue(curr+Integer.parseInt(x));
   }

private int jButton3ClickCount = 0;

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pikachu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pikachu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pikachu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pikachu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pikachu().setVisible(true);
            }
        });
    }
    
    
    
     
    class UpdateImageListener implements ActionListener {
    @Override
    public void actionPerformed(ActionEvent e) {
        updateImage();
    }
}
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JProgressBar jProgressBar1;
    // End of variables declaration//GEN-END:variables
private void setIconImage() {
       setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icon.png"))); 
    }

}



